### ISSUE TITLE
Change package from `org.apache.jasper` to something in `org.eclipse.*` namespace

### ISSUE THREAD

**Issue by joakime** [eclipse-ee4j/wasp#29]
This wasp implementation overlaps in package namespace with the official apache/tomcat managed Apache Jasper.

This should be changed.

I propose `org.eclipse.wasp` as the new name.

**Comment by arjantijms** [comment]
Manny of the other projects, including newer ones, use `org.glassfish.something`, although I think at least one newer project used `org.eclipse.something`. 

Given the many other projects at Eclipse, I personally find `org.eclipse.[project name]` a wee bit too general, but that may just be me.
