### ISSUE TITLE
Implement new Jakarta Pages API

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/wasp#43]
* getErrorOnELNotFound()

**Comment by volosied** [comment]
Since Glassfish uses WaSP, is this implementation detail causing the JSTL / JSP TCK errors below? 

`jakarta.el.PropertyNotFoundException: ELResolver cannot handle a null base Object with identifier <some name>`

https://github.com/eclipse-ee4j/jakartaee-tck/issues/882#issuecomment-1064272480

**Comment by scottmarlow** [comment]
Is `java.lang.ClassNotFoundException: org.glassfish.wasp.runtime.ProtectedFunctionMapper$1 not found by org.glassfish.wasp.wasp` one of the failures expected to be fixed for this issue?  

https://gist.github.com/scottmarlow/a25009933d7062154797b01c09306d2e shows the failure.

**Comment by arjantijms** [comment]
> Since Glassfish uses WaSP, is this implementation detail causing the JSTL / JSP TCK errors below?

Might wel be the case indeed.

**Comment by alwin-joseph** [comment]
FYI we have 9 test failures in pages TCK https://github.com/eclipse-ee4j/jakartaee-tck/issues/832 when run with glassfish latest, which were suggested as issues with glassfish https://github.com/eclipse-ee4j/jakartaee-tck/issues/832#issuecomment-1035040022

**Comment by volosied** [comment]
Made a little bit of progress here: https://github.com/volosied/wasp/commit/c6fd820f7ba432d93da6a622085a66fc18ccb529

However, it's not yet fully functional. 

After looking at this feature, I have doubts it will fix the `jakarta.el.PropertyNotFoundException: ELResolver cannot handle a null base Object with identifier <some name>` error we've seen in the TCKs.

**Comment by arjantijms** [comment]
@alwin-joseph the TCK now passes fully with this PR: https://github.com/eclipse-ee4j/wasp/pull/45

```
[INFO]      [exec] [javatest.batch] ********************************************************************************
[INFO]      [exec] [javatest.batch] Number of tests completed:  708 (708 passed, 0 failed, 0 with errors)
[INFO]      [exec] [javatest.batch] Number of tests remaining:  0
[INFO]      [exec] [javatest.batch] ********************************************************************************
[INFO]      [exec] [javatest.batch] Completed running 708 tests.
[INFO]      [exec] [javatest.batch] Number of Tests Passed      = 708
[INFO]      [exec] [javatest.batch] Number of Tests Failed      = 0
[INFO]      [exec] [javatest.batch] Number of Tests with Errors = 0
[INFO]      [exec] [javatest.batch] ********************************************************************************
```

**Comment by alwin-joseph** [comment]
> @alwin-joseph the TCK now passes fully with this PR: #45
> 
> ```
> [INFO]      [exec] [javatest.batch] ********************************************************************************
> [INFO]      [exec] [javatest.batch] Number of tests completed:  708 (708 passed, 0 failed, 0 with errors)
> [INFO]      [exec] [javatest.batch] Number of tests remaining:  0
> [INFO]      [exec] [javatest.batch] ********************************************************************************
> [INFO]      [exec] [javatest.batch] Completed running 708 tests.
> [INFO]      [exec] [javatest.batch] Number of Tests Passed      = 708
> [INFO]      [exec] [javatest.batch] Number of Tests Failed      = 0
> [INFO]      [exec] [javatest.batch] Number of Tests with Errors = 0
> [INFO]      [exec] [javatest.batch] ********************************************************************************
> ```

Thanks! Will run the TCK once WASP is updated in glassfish.

**Comment by arjantijms** [comment]
@alwin-joseph the new WaSP M2 is in GlassFIsh now. It's likely in the currently nightly of GF as well.
