### ISSUE TITLE
org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.0 has invalid jstl-api dependency

### ISSUE THREAD

**Issue by zman0900** [eclipse-ee4j/wasp#57]
The [3.0.0 version of jstl in Maven Central](https://search.maven.org/artifact/org.glassfish.web/jakarta.servlet.jsp.jstl/3.0.0/jar) has a dependency on version "3.0.0-RC1" of jstl-api, which was never released to Maven Central:

```xml
    <dependency>
      <groupId>jakarta.servlet.jsp.jstl</groupId>
      <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
      <version>3.0.0-RC1</version>
      <scope>compile</scope>
    </dependency>
```

Please release updated version of jstl which has correct "3.0.0" jstl-api dependency.

**Comment by pnicolucci** [comment]
@zman0900 ok to close this issue now?

**Comment by zman0900** [comment]
Seems fine to me.  I noticed that scope for the jstl-api dependency changed from compile to provided.  Not sure if that was intentional, but it did mean that I needed to now add direct runtime dependency for jstl-api, at least for use with Tomcat, where previously I only needed runtime dependency on jstl.
