### ISSUE TITLE
Timeline for release 4.0.0 to support servlet 6.1/ee11 spec

### ISSUE THREAD

**Issue by janbartel** [eclipse-ee4j/wasp#75]
Is there are timeline for a release of wasp that supports the servlet 6.1/ee11 spec please? Jetty would like to move to it, but there are no artifacts for it available in maven central.

**Comment by arjantijms** [comment]
It is released now ;)

https://repo1.maven.org/maven2/org/glassfish/wasp/wasp/4.0.0/

Essentiallu it's M2 promoted to final as no blockers were found and no updates came up between that release and now.
